# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

    direction_api_key: AIzaSyCTgoKydZ7BAGz7q7B2lgJKODHQQ7BF40I
    weather_api_key: 366e4cce74655550b9f3df81401bef1a

services:

    app.direction:
        class: ApiBundle\Direction\Direction
        public: true
        arguments: ["@csa_guzzle.client.direction","@jms_serializer", "%direction_api_key%"]

    app.weather:
        class: ApiBundle\Weather\Weather
        public: true
        arguments: ['@csa_guzzle.client.weather','@jms_serializer',%weather_api_key%]
