<?php

namespace ApiBundle\Repository;

/**
 * JourneyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JourneyPlaylistRepository extends \Doctrine\ORM\EntityRepository
{
}
